[package]
name = "iced-plotter"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.21", features = ["derive"] }
iced = { version = "0.14.0", features = ["wgpu", "debug", "tokio"] }

